import React from "react";

const Apollo = () => {
  return (
    <>
      <div>
        <iframe
          className="p-12"
          width="1920"
          height="1080"
          src="https://www.eporner.com/embed/eVgWdbSUufy/"
          aria-controls="enable"
          allowFullScreen
        ></iframe>
        <iframe
          className="p-12"
          width="1920"
          height="1080"
          src="https://www.eporner.com/embed/c2d8tOMqifu/"
          aria-controls="enable"
          allowFullScreen
        ></iframe>
        <iframe
          className="p-12"
          width="1920"
          height="1080"
          src="https://www.eporner.com/embed/FdxTBZjCn2p/"
          aria-controls="enable"
          allowFullScreen
        ></iframe>
        <iframe
          className="p-12"
          width="1920"
          height="1080"
          src="https://www.eporner.com/embed/AvLi5e5Pa90/"
          aria-controls="enable"
          allowFullScreen
        ></iframe>
        <iframe
          className="p-12"
          width="1920"
          height="1080"
          src="https://www.eporner.com/embed/zodCASZYukW/"
          aria-controls="enable"
          allowFullScreen
        ></iframe>
        <iframe
          className="p-12"
          width="1920"
          height="1080"
          src="https://www.eporner.com/embed/BN00h9irndl/"
          aria-controls="enable"
          allowFullScreen
        ></iframe>
        <iframe
          className="p-12"
          width="1920"
          height="1080"
          src="https://www.eporner.com/embed/jXQtbVUr4DM/"
          aria-controls="enable"
          allowFullScreen
        ></iframe>
        <iframe
          className="p-12"
          width="1920"
          height="1080"
          src="https://www.eporner.com/embed/ecTlSotWKZZ/"
          aria-controls="enable"
          allowFullScreen
        ></iframe>
        <iframe
          className="p-12"
          width="1920"
          height="1080"
          src="https://www.eporner.com/embed/cnU5qir5mIz/"
          aria-controls="enable"
          allowFullScreen
        ></iframe>
        <iframe
          className="p-12"
          width="1920"
          height="1080"
          src="https://www.eporner.com/embed/8A7gz3I4Rwt/"
          aria-controls="enable"
          allowFullScreen
        ></iframe>
        <iframe
          className="p-12"
          width="1920"
          height="1080"
          src="https://www.eporner.com/embed/4OP7OA8SjUi/"
          aria-controls="enable"
          allowFullScreen
        ></iframe>
        <iframe
          className="p-12"
          width="1920"
          height="1080"
          src="https://www.eporner.com/embed/r4pkcu9wRcB/"
          aria-controls="enable"
          allowFullScreen
        ></iframe>
        <iframe
          className="p-12"
          width="1920"
          height="1080"
          src="https://www.eporner.com/embed/nx8mVIlSbLY/"
          aria-controls="enable"
          allowFullScreen
        ></iframe>
        <iframe
          className="p-12"
          width="1920"
          height="1080"
          src="https://www.eporner.com/embed/KOO4smnHAuI/"
          aria-controls="enable"
          allowFullScreen
        ></iframe>
        <iframe
          className="p-12"
          width="1920"
          height="1080"
          src="https://www.eporner.com/embed/VvptCiEy0a7/"
          aria-controls="enable"
          allowFullScreen
        ></iframe>
        <iframe
          className="p-12"
          width="1920"
          height="1080"
          src="https://www.eporner.com/embed/E1EHTRQ6iAh/"
          aria-controls="enable"
          allowFullScreen
        ></iframe>
        <iframe
          className="p-12"
          width="1920"
          height="1080"
          src="https://www.eporner.com/embed/OGC0N9sLq0F/"
          aria-controls="enable"
          allowFullScreen
        ></iframe>
        <iframe
          className="p-12"
          width="1920"
          height="1080"
          src="https://www.eporner.com/embed/ZQRnBv8J4dD/" 
          aria-controls="enable"
          allowFullScreen
        ></iframe>
      </div>
    </>
  );
};

export default Apollo;
